spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Paper
    username: root
    password: jys123
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  servlet:
    multipart:
        max-file-size: 10MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名(代码中)和下划线命名(数据库中)的自动转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080